### ISSUE TITLE
Add fallback if the examine option has been removed by another plugin

### ISSUE THREAD

**Issue by CalebBarnes** [donth77/loot-lookup-plugin#12]
https://github.com/donth77/loot-lookup-plugin/blob/bd93c4fc56030d55fd8e0b10a030de9e22df899a/src/main/java/com/lootlookup/LootLookupPlugin.java#L110-L112

Right now if there is an attackable NPC but it has no examine menu entry (menu entry removed by different plugin) then there will be no loot lookup menu entry added.

**Comment by donth77** [comment]
I think this should achieve the same result without checking for the "Examine" text:

[https://github.com/donth77/loot-lookup-plugin/commit/b10af87798e842b276d480373ef293f9d6528ebd#diff-e37addb33b084599af06f9ca8f187542da8cf268727dea17596d33a7717eab5cR116](https://github.com/donth77/loot-lookup-plugin/commit/b10af87798e842b276d480373ef293f9d6528ebd#diff-e37addb33b084599af06f9ca8f187542da8cf268727dea17596d33a7717eab5cR116)

**Comment by donth77** [comment]
@CalebBarnes 

I think this should achieve the same result without checking for the "Examine" text:

[https://github.com/donth77/loot-lookup-plugin/commit/b10af87798e842b276d480373ef293f9d6528ebd#diff-e37addb33b084599af06f9ca8f187542da8cf268727dea17596d33a7717eab5cR115](https://github.com/donth77/loot-lookup-plugin/commit/b10af87798e842b276d480373ef293f9d6528ebd#diff-e37addb33b084599af06f9ca8f187542da8cf268727dea17596d33a7717eab5cR115)

**Comment by CalebBarnes** [comment]
That is perfect, so it would just add the option as the last item in the list?
```java
  MenuEntry entryToAppendOn = menuEntries[menuEntries.length - 1];
  ```
  

It would behave slightly differently than it does now if you are okay with that.
For example, the option would appear *after* the examine menu entry for most users, instead of before the examine option like it is now.

And then also if you are right-clicking on a pile of mobs, it would probably add all of the new menu entries to the very bottom but that might even make it easier for the user to select them.

I am totally okay with this solution, just wanted to make sure you know it would change things a little bit!
