### ISSUE TITLE
Dusk/Dawn No file for loot

### ISSUE THREAD

**Issue by zeixic** [donth77/loot-lookup-plugin#15]
Dusk/Dawn when right clicked and look for loot, side bar can't find boss.

**Comment by donth77** [comment]
The wiki pages for [Dusk ](https://oldschool.runescape.wiki/w/Dusk#Drops) and [Dawn ](https://oldschool.runescape.wiki/w/Dawn#Drops) have an empty drops section that link to the [Grotesque Guardians](https://oldschool.runescape.wiki/w/Grotesque_Guardians#Drops) page. I'll have the plugin handle this as an edge case.

**Comment by donth77** [comment]
This should be fixed in v1.1.6.

![Dusk](https://i.imgur.com/Qr7wOSs.png)
