### ISSUE TITLE
Chompy Bird Has No "Lookup" Text

### ISSUE THREAD

**Issue by PJGJ210** [donth77/loot-lookup-plugin#16]
![image](https://user-images.githubusercontent.com/16944807/181278142-74f81d1e-4a68-4279-b79d-d5e03846f253.png)
![image](https://user-images.githubusercontent.com/16944807/181278423-57efd16a-09e4-4054-91bd-135ad735a6f9.png)
![image](https://user-images.githubusercontent.com/16944807/181278253-76523af3-f91d-4b96-a2cf-b68b5211def8.png)

**Comment by donth77** [comment]
Thanks for the issue. This should be fixed in the next version v1.1.6.

![Image](https://i.imgur.com/SPBpNE8.png)
