### ISSUE TITLE
Unclear whether drops are noted

### ISSUE THREAD

**Issue by shaunie1996** [donth77/loot-lookup-plugin#7]
Brine rats are a good example to display this issue, as far as I can tell there is no indicator which fish drop chance is for noted, and which is for not. Perhaps a toggle to show a banknote icon on noted drops, assuming the scraped data includes that?

**Comment by donth77** [comment]
Thanks for the issue.

During the parsing, the " (noted)" portion of the quantity is currently removed. I've pushed a commit that displays noted drops with a note image and includes the "(noted)" text in cases where it would reasonably fit. This is what Brine rat would look like in v1.1.4:

![Brine rat](https://i.imgur.com/iCW5yNr.png)
